import "./globals.css";
import Navbar from "@/components/navbar";  // import navbar

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />   {/* อยู่บนสุดทุกหน้า */}
        <div className="pt-16">{children}</div> {/* เว้น padding-top กัน Navbar ทับ */}
      </body>
    </html>
  );
}
